tasks

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,8 +1,35 @@
 #!/usr/bin/env bash
 # script that installs nginx server
 
-sudo apt-get -y update;
-sudo apt-get -y install nginx;
+sudo apt-get -y update  && \
+sudo apt-get -y install nginx
 sudo ufw allow 'Nginx HTTP';
-sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location \ {
+        }
+    }
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
 sudo service nginx start;
